Implement class attribute for reads. Fixes #10
chris-zen/htsget-mvp pull request #19
Opened 2021-04-12 07:10 UTC by mmalenic

I've attempted to implement the class attribute for reads, according to the spec.
Let me know if I'm on the right track, because I'm not certain that this is correct.

2021-04-12 13:15 UTC, brainstorm commented
Marco, this looks good, but can you please rebase? There seem to be conflicts right now.

2021-04-12 21:20 UTC, chris-zen requested changes
Hi @mmalenic, thank you very much for the contribution !

There are some comments I'd like you to address before merging, but overall it looks great !

Also, please make sure you format the code and pass al the clippy warnings and all the tests before committing. I guess that you will get the Actions running after you rebase your code, unfortunately there was a refactor recently.

```
cargo fmt --all
cargo clippy --all-targets -- -Dclippy::all -Dwarnings
cargo test
```

Keep the great work ;-)

2021-04-12 21:20 UTC, chris-zen commented on htsget-search/src/storage/local.rs
> +    };
Could you please move the common part into an intermediate variable?

```suggestion
    let url = Url::new(format!("file://{}", path.to_string_lossy())).with_headers(headers);
    let url = match options.class {
      Some(class) => url.with_class(class),
      None => url,
    };
    Ok(url)
```

2021-04-12 21:20 UTC, chris-zen commented on htsget-search/src/storage/mod.rs
> +  pub range: BytesRange,
We can skip making this `pub` for now.

2021-04-12 21:20 UTC, chris-zen commented on htsget-search/src/htsget/bam.rs
> +    query: Query,
Either you don't pass the class and get it from the query, or don't pass the query and add the format, but please don't mix them.

Option 1:
```rust
 fn format_urls(
    &self,
    query: Query,
    bam_key: &String,
    byte_ranges: Vec<BytesRange>,
  ) -> Result<Response> {
```

Option 2:
```rust
 fn format_urls(
    &self,
    format: Option<Format>,
    class: Option<Class>,
    bam_key: &String,
    byte_ranges: Vec<BytesRange>,
  ) -> Result<Response> {
```

2021-04-12 21:20 UTC, chris-zen commented on htsget-search/src/htsget/bam.rs
> +use crate::htsget::Class;
could you please move this `Classs` to the previous `htsget::{ ... }` use declaration ?

2021-04-13 05:37 UTC, mmalenic commented
Hi @chris-zen

Thanks for the feedback!
I've made those suggested changes.

2021-04-13 21:01 UTC, chris-zen approved these changes
@mmalenic thank you very much. Great work !

2021-04-13 21:03 UTC, merged